version: '3.4'

services:
  catalog.db.ui:
    image: mongoclient/mongoclient
  catalog.db:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
volumes:
  mongo_data:
  mongo_ui: